const {Vec3}=require('vec3'),fs=require('node:fs'),path=require('node:path')
function portalBlueprint(p){return [[1,0],[2,0],[0,1],[3,1],[0,2],[3,2],[0,3],[3,3],[1,4],[2,4]].map(([x,y])=>p.offset(x,y,0))}
function triangulate(a,b){const cross=(v,w)=>v.x*w.z-v.z*w.x,d=cross(a.direction,b.direction);if(Math.abs(d)<0.08)return null;const delta={x:b.origin.x-a.origin.x,z:b.origin.z-a.origin.z},t=cross(delta,b.direction)/d,u=cross(delta,a.direction)/d;if(t<0||u<0||t>10000||u>10000)return null;return {x:a.origin.x+t*a.direction.x,z:a.origin.z+t*a.direction.z}}
function createEndgame(bot,{check,near,acquire,explore,huntMob,sleep,campaign},file=path.join(__dirname,'logs/endgame.json')){
 let saved={portals:{},eyes:[]};try{saved={...saved,...JSON.parse(fs.readFileSync(file))}}catch{}
 const deadCrystals=new Set(saved.destroyedCrystals||[]);bot.on('entityDead',entity=>{if(entity.name==='end_crystal'&&bot.game.dimension.includes('the_end')){deadCrystals.add(entity.uuid||entity.position.toString());saved.destroyedCrystals=[...deadCrystals];persist();if(deadCrystals.size>=10)campaign.record('crystals',{source:'server_entity_dead',count:deadCrystals.size})}})
 const persist=()=>{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(saved))}
 const items=()=>bot.inventory.items(),count=n=>items().filter(i=>i.name===n).reduce((n,i)=>n+i.count,0)
 async function setBlock(p,name,token){check(token);if(bot.blockAt(p)?.name===name)return;const current=bot.blockAt(p);if(!current||!['air','cave_air','fire'].includes(current.name))throw new Error('포털 부지가 비어 있지 않습니다.');for(const off of [new Vec3(0,-1,0),new Vec3(-1,0,0),new Vec3(1,0,0),new Vec3(0,0,-1),new Vec3(0,0,1)]){const ref=bot.blockAt(p.plus(off));if(ref?.boundingBox!=='block')continue;await near(p,3,token);check(token);await bot.equip(items().find(i=>i.name===name),'hand');await bot.placeBlock(ref,off.scaled(-1));check(token);if(bot.blockAt(p)?.name===name)return}throw new Error('포털 블록 설치에 필요한 발판이 없습니다.')}
 async function buildPortal(token){let existing=bot.findBlock({matching:b=>b.name==='nether_portal',maxDistance:32});if(existing)return existing
 await acquire('obsidian',saved.portalSite?Math.max(1,10-portalBlueprint(new Vec3(saved.portalSite.x,saved.portalSite.y,saved.portalSite.z)).filter(p=>bot.blockAt(p)?.name==='obsidian').length):10,token);await acquire('flint_and_steel',1,token);await acquire('cobblestone',4,token)
 let p=saved.portalSite?new Vec3(saved.portalSite.x,saved.portalSite.y,saved.portalSite.z):null
 if(!p){const start=bot.entity.position.floored();outer:for(let x=-8;x<=8;x++)for(let z=-8;z<=8;z++){const q=start.offset(x,0,z);let clear=true;for(let xx=0;xx<4;xx++){if(bot.blockAt(q.offset(xx,-1,0))?.boundingBox!=='block')clear=false;for(let y=0;y<5;y++)if(bot.blockAt(q.offset(xx,y,0))?.name!=='air')clear=false}if(clear){p=q;break outer}}if(!p)throw new Error('4×5 포털 부지가 없습니다.');saved.portalSite=p;persist()}
 // Disposable corner blocks give every frame segment a real placement face.
 for(const q of [p,p.offset(3,0,0)])await setBlock(q,'cobblestone',token)
 for(const q of portalBlueprint(p).filter(q=>q.y<p.y+4))await setBlock(q,'obsidian',token)
 for(const q of [p.offset(0,4,0),p.offset(3,4,0)])await setBlock(q,'cobblestone',token)
 for(const q of portalBlueprint(p).filter(q=>q.y===p.y+4))await setBlock(q,'obsidian',token)
 await near(p.offset(1,1,0),2,token);await bot.equip(items().find(i=>i.name==='flint_and_steel'),'hand');await bot.activateBlock(bot.blockAt(p.offset(1,0,0)),new Vec3(0,1,0));await sleep(800);check(token);existing=bot.findBlock({matching:b=>b.name==='nether_portal',maxDistance:12});if(!existing)throw new Error('포털 활성화를 확인하지 못했습니다.');return existing
 }
 async function travel(token){let portal=bot.findBlock({matching:b=>b.name==='nether_portal',maxDistance:64});if(!portal){const old=saved.portals[bot.game.dimension];if(old){const target=new Vec3(old.x,old.y,old.z),delta=target.minus(bot.entity.position),distance=Math.hypot(delta.x,delta.z);if(distance>30){await near(bot.entity.position.offset(delta.x/distance*24,0,delta.z/distance*24),3,token);return false}await near(target,3,token);portal=bot.findBlock({matching:b=>b.name==='nether_portal',maxDistance:12})}}if(!portal)throw new Error('주변 포털이 없습니다. 포털 건설 또는 귀환 좌표 접근이 필요합니다.');const from=bot.game.dimension;saved.portals[from]=portal.position;persist();await near(portal.position,0,token);const until=Date.now()+15000;while(bot.game.dimension===from&&Date.now()<until){check(token);await sleep(300)}check(token);if(bot.game.dimension===from)throw new Error('포털 차원 이동 시간 초과');saved.portals[bot.game.dimension]=bot.entity.position;persist()}
 async function fortress(token){const block=bot.findBlock({matching:b=>['nether_bricks','nether_brick_fence','nether_brick_stairs'].includes(b.name),maxDistance:64});if(block){await near(block.position,3,token);return block.position}await explore(token);throw new Error('불러온 지형에서 네더 요새를 찾지 못했습니다. 탐색을 이어가야 합니다.')}
 async function eye(token){await acquire('ender_eye',1,token);const origin=bot.entity.position.clone();let entity=null;const listener=e=>{if(['eye_of_ender','ender_signal'].includes(e.name)&&e.position.distanceTo(origin)<6)entity=e};bot.on('entitySpawn',listener)
 try{await bot.equip(items().find(i=>i.name==='ender_eye'),'hand');bot.activateItem();const until=Date.now()+2500;while(!entity&&Date.now()<until){check(token);await sleep(50)}if(!entity)throw new Error('던진 엔더의 눈을 관측하지 못했습니다.');await sleep(1200);check(token);const dx=entity.position.x-origin.x,dz=entity.position.z-origin.z,len=Math.hypot(dx,dz);if(len<4&&entity.position.y<origin.y+2){await near(origin.offset(2,-3,0),1,token);return}if(len<1)throw new Error('엔더의 눈 방향 측정 실패');const ray={origin,direction:{x:dx/len,z:dz/len}};saved.eyes.push(ray);saved.eyes=saved.eyes.slice(-8);const previous=saved.eyes.slice(0,-1).reverse().find(e=>Math.hypot(e.origin.x-origin.x,e.origin.z-origin.z)>16);const target=previous&&triangulate(previous,ray);saved.strongholdEstimate=target||null;persist();const dest=target?new Vec3(target.x,origin.y,target.z):origin.offset(ray.direction.x*24,0,ray.direction.z*24);const delta=dest.minus(origin),distance=Math.hypot(delta.x,delta.z);await near(distance>24?origin.offset(delta.x/distance*24,0,delta.z/distance*24):dest,4,token)}finally{bot.removeListener('entitySpawn',listener);bot.deactivateItem()}}
 async function stronghold(token){const frame=bot.findBlock({matching:b=>b.name==='end_portal_frame',maxDistance:64});if(frame){campaign.record('stronghold',{position:frame.position,dimension:bot.game.dimension,source:'observed_portal_frame'});return}await eye(token)}
 async function enterEnd(token){const frames=bot.findBlocks({matching:b=>b.name==='end_portal_frame',maxDistance:48,count:12});if(frames.length!==12)throw new Error('엔드 포털 테두리 12개를 모두 확인해야 합니다.');const empty=frames.filter(p=>!bot.blockAt(p).getProperties().eye);if(empty.length)await acquire('ender_eye',empty.length,token);for(const p of empty){await near(p,3,token);check(token);await bot.equip(items().find(i=>i.name==='ender_eye'),'hand');await bot.activateBlock(bot.blockAt(p));await sleep(250);check(token);if(!bot.blockAt(p).getProperties().eye)throw new Error('엔더의 눈 설치를 확인하지 못했습니다.')}
 const portal=bot.findBlock({matching:b=>b.name==='end_portal',maxDistance:32});if(!portal)throw new Error('엔드 포털이 열리지 않았습니다.');await near(portal.position,0,token);for(let i=0;i<40&&!bot.game.dimension.includes('the_end');i++){check(token);await sleep(250)}if(!bot.game.dimension.includes('the_end'))throw new Error('엔드 이동을 확인하지 못했습니다.')}
 async function shoot(entity,token){await acquire('bow',1,token);if(!count('arrow'))await acquire('arrow',16,token);let p=entity.position.offset(0,(entity.height||1)/2,0),d=bot.entity.position.distanceTo(p);if(d>48)await near(entity.position,24,token);check(token);p=entity.position.offset(0,(entity.height||1)/2,0);d=bot.entity.position.distanceTo(p);await bot.equip(items().find(i=>i.name==='bow'),'hand');await bot.lookAt(p.offset(0,Math.min(12,d*d*0.003),0));bot.activateItem();try{for(let i=0;i<6;i++){check(token);await sleep(200)}}finally{bot.deactivateItem()}await sleep(700);check(token)}
 async function crystals(token){if(!bot.game.dimension.includes('the_end'))throw new Error('엔드에서만 수정을 탐색합니다.');const entities=Object.values(bot.entities).filter(e=>e.name==='end_crystal');if(!entities.length)throw new Error('현재 보이는 수정이 없습니다. 섬 전체 제거 여부는 아직 확인되지 않았습니다.');for(const entity of entities.slice(0,3)){
 const bars=bot.findBlocks({matching:b=>b.name==='iron_bars',point:entity.position,maxDistance:5,count:80});
 if(bars.length){await acquire('cobblestone',64,token);await acquire('iron_pickaxe',1,token);const movement=bot.pathfinder.movements,old=movement.allow1by1towers;movement.allow1by1towers=true;try{for(const p of bars){check(token);await near(p,3,token);await bot.equip(items().find(i=>i.name==='iron_pickaxe'),'hand');const b=bot.blockAt(p);if(b?.name==='iron_bars')await bot.dig(b)}}finally{movement.allow1by1towers=old}if(bot.entity.position.distanceTo(entity.position)<9){const away=bot.entity.position.minus(entity.position);const len=Math.hypot(away.x,away.z)||1;await near(bot.entity.position.offset(away.x/len*10,0,away.z/len*10),2,token)}}
 for(let i=0;i<5&&bot.entities[entity.id];i++)await shoot(entity,token);if(bot.entities[entity.id])throw new Error('수정 사격이 빗나갔습니다. 다른 위치에서 다시 시도합니다.')
 }}
 async function dragon(token){if(!bot.game.dimension.includes('the_end'))throw new Error('엔드 진입이 필요합니다.');const target=Object.values(bot.entities).find(e=>e.name==='ender_dragon');if(!target)throw new Error('드래곤을 관측하지 못했습니다.');for(let i=0;i<8&&bot.entities[target.id];i++){check(token);if(bot.health<12)throw new Error('드래곤 전투 중 체력이 낮습니다. 회복이 필요합니다.');await shoot(target,token)}}
 async function barter(token){await acquire('gold_ingot',8,token);const piglin=Object.values(bot.entities).find(e=>e.name==='piglin');if(!piglin)throw new Error('주변에 피글린이 없습니다.');if(!bot.inventory.slots.slice(5,9).some(i=>i?.name.startsWith('golden_')))throw new Error('피글린 거래 전 금 방어구를 착용해야 합니다.');await near(piglin.position,3,token);for(let i=0;i<8&&count('gold_ingot');i++){check(token);await bot.lookAt(piglin.position);await bot.toss(bot.registry.itemsByName.gold_ingot.id,null,1);for(let j=0;j<14;j++){check(token);await sleep(500)}for(const drop of Object.values(bot.entities).filter(e=>e.name==='item'&&e.position.distanceTo(piglin.position)<5))await near(drop.position,1,token)}}
 return {buildPortal,travel,fortress,stronghold,enterEnd,crystals,dragon,barter,status:()=>saved}
}
module.exports={createEndgame,portalBlueprint,triangulate}
