const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{Vec3}=require('vec3')
const {blueprint,furnishingPlan,requirements,designPreview,createStructures,constructionStand}=require('../structures'),{castleEntrances,towers}=require('../castle'),{parseKnownGoals,interpret}=require('../missions'),{materialPlan}=require('../acquisition'),{createMinimap,tile}=require('../minimap')
const registry=require('minecraft-data')('1.21.1'),cells=blueprint('castle'),furniture=furnishingPlan('castle'),key=p=>`${p.x},${p.y},${p.z}`,occupied=new Map(cells.map(c=>[key(c),c])),temp=fs.mkdtempSync(path.join(os.tmpdir(),'mc-castle-'))
async function main(){try{
 assert.equal(new Set(cells.map(key)).size,cells.length);assert.equal(new Set(furniture.map(f=>key(f.p))).size,furniture.length);assert(!furniture.some(f=>occupied.has(key(f.p))))
 for(const text of ['유럽풍 성 지어줘','성을 지어줘','중세 성 건축해줘','성곽 만들어줘','캐슬 지어줘','성채를 만들어줘'])assert.equal(parseKnownGoals(text,registry)[0].design,'castle',text)
 assert.equal((await interpret('유럽풍 성을 지어줘',registry))[0].design,'castle');await assert.rejects(()=>interpret('궁전을 지어줘',registry),/전용 설계/)
 assert.deepEqual(parseKnownGoals('성을 짓고 밀 농사 지어줘',registry).map(g=>g.type),['build','farm']);assert.equal(cells.filter(c=>c.material==='door'&&!c.generated).length,2)
 assert.equal(furniture.filter(f=>f.material==='ladder').length,20);const bedIndex=furniture.findIndex(f=>f.material==='bed');assert(!furniture.slice(0,bedIndex).some(f=>f.p.equals(furniture[bedIndex].p.offset(-1,0,0))),'keep the bed placement approach clear until orientation is set');assert.equal(requirements('castle').white_bed,1);assert.equal(requirements('castle').oak_door,2)
 for(const t of towers){assert(cells.some(c=>c.x===t.x&&c.z===t.z&&c.y===6));assert(!occupied.has(`${t.x+1},5,${t.z+1}`),'ladder shaft stays open through the tower platform');assert(!occupied.has(`${t.x+1},1,${t.z+t.entry}`),'each tower has a usable courtyard entrance')}
 assert(!occupied.has('7,4,9'),'keep roof is hollow');assert(cells.some(c=>c.x===7&&c.y===6&&c.z===9),'keep ridge');assert(!occupied.has('7,1,4'),'gate connects through an open courtyard')
 // Every structure block has an already-built attachment face, or is a door
 // half produced by the preceding lower-half placement. Terrain supports y=0.
 const placed=new Set();for(const c of cells){if(c.generated||c.material==='door')continue;assert(c.y===0||[[0,-1,0],[-1,0,0],[1,0,0],[0,0,-1],[0,0,1]].some(([x,y,z])=>placed.has(`${c.x+x},${c.y+y},${c.z+z}`)),`unsupported placement order at ${key(c)} ${c.phase}`);placed.add(key(c))}
 for(const [item,n]of Object.entries(requirements('castle'))){assert(registry.itemsByName[item]);assert(!JSON.stringify(materialPlan(item,n,[])).includes('unknown_source'),`missing material path ${item}`)}
 const origin={x:4,y:65,z:4},file=path.join(temp,'structures.json'),recordKey=`${process.env.MC_HOST||'127.0.0.1'}:${process.env.MC_PORT||25565}:overworld:castle`;fs.writeFileSync(file,JSON.stringify({[recordKey]:{origin,wood:'oak',version:3}}))
 const bot={game:{dimension:'overworld'},entity:{position:new Vec3(11,66,9)},inventory:{items:()=>[]},blockAt:p=>{const c=occupied.get(`${p.x-4},${p.y-65},${p.z-4}`);return {name:c?.material==='door'?'oak_door':'air',getProperties:()=>({half:c?.part})}}},structures=createStructures(bot,{},file)
 assert.equal(structures.status('castle').stages.length,6);assert(structures.protects(new Vec3(4,65,4)));assert.equal(structures.doorCrossing(new Vec3(11,65,0),new Vec3(11,66,13)).door.z,4,'enter outer gate first');assert.equal(structures.doorCrossing(new Vec3(11,66,6),new Vec3(11,66,13)).door.z,11,'then enter keep');assert.equal(structures.doorCrossing(new Vec3(11,66,13),new Vec3(11,65,0)).door.z,11,'exit inner door first');assert.equal(castleEntrances(origin).length,2)
 assert.equal(structures.ladderAccess(new Vec3(5,66,7),new Vec3(4,71,5)),null,'do not use an incomplete ladder shaft');const oldBlockAt=bot.blockAt,ladderCells=new Set(furnishingPlan('castle',origin).filter(f=>f.material==='ladder').map(f=>key(f.p)));bot.blockAt=p=>ladderCells.has(key(p))?{name:'ladder'}:oldBlockAt(p);const access=structures.ladderAccess(new Vec3(5,66,7),new Vec3(4,71,5));assert.deepEqual(access.bottom,new Vec3(5,66,5));assert.deepEqual(access.top,new Vec3(4,71,5));assert.equal(structures.ladderAccess(new Vec3(4,71,5),new Vec3(10,70,12)),null,'already elevated navigation needs no repeated ascent')
 let now=0,calls=0;const mapBot={username:'LayaBot',game:{dimension:'overworld'},entity:{position:new Vec3(0,65,0)},entities:{1:{type:'player',username:'human',position:new Vec3(2,65,0)}},blockAt:p=>{calls++;return p.x<0?null:{name:p.y<=64?'grass_block':'air',boundingBox:p.y<=64?'block':'empty'}}},map=createMinimap(mapBot,{now:()=>now}),m=map.snapshot();assert.equal(m.cells[0],0,'unloaded terrain stays unknown');assert(m.cells.includes(tile('grass_block')));const reads=calls;assert.equal(map.snapshot(),m);assert.equal(calls,reads,'reuse observed terrain between scans');assert.equal(map.markers()[0].type,'player');now=3000;map.snapshot();assert(calls>reads)
 const footBot={entity:{position:new Vec3(4,65,4)},blockAt:p=>({name:p.y<=65?'cobblestone':'air',boundingBox:p.y<=65?'block':'empty'})};assert.equal(constructionStand(footBot,new Vec3(4,65,4)).y,66,'step aside onto the top of a raised foundation rather than pathfinding into a solid block');assert.equal(designPreview('castle').width,15);console.log('PASS castle commands, independent rooms/towers/gates, hollow roof and ladder shafts, attachment order, recipe coverage, persisted stages, protected foundation, nested entrance routing, minimap unknown terrain/cache/markers')
}finally{fs.rmSync(temp,{recursive:true,force:true})}}
main().catch(e=>{console.error(e);process.exitCode=1})
