// Real production construction; all administrative fixtures use port 25566.
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{execFileSync,fork}=require('node:child_process')
const {requirements,blueprint,furnishingPlan}=require('../structures')
assert.equal(Number(process.env.MC_TEST_PORT||25566),25566)
const rcon=cmd=>execFileSync('docker',['exec','minecraft-laya-validation','rcon-cli',cmd],{encoding:'utf8',timeout:10000}),sleep=ms=>new Promise(r=>setTimeout(r,ms)),temp=fs.mkdtempSync(path.join(os.tmpdir(),'mc-castle-live-')),origin={x:4,y:65,z:4}
let child,state,output='',beforeDeath,afterDeath
async function wait(predicate,timeout=40000){const end=Date.now()+timeout;while(Date.now()<end){if(predicate())return;if(child?.exitCode!=null)throw Error('Bot exited: '+output.slice(-1800));if(state?.auto?.failures>=6)throw Error('Goal paused: '+state.auto.reason);await sleep(150)}throw Error('Timeout: '+JSON.stringify({auto:state?.auto?.phase,reason:state?.auto?.reason,building:state?.buildings,position:state?.position,recovery:state?.recovery})+'\n'+output.slice(-1800))}
async function main(){
 const resumeDir=process.env.CASTLE_RESUME_DIR;if(resumeDir)fs.cpSync(resumeDir,temp,{recursive:true});
 if(!resumeDir)for(const cmd of ['gamerule doMobSpawning false','gamerule doDaylightCycle false','gamerule keepInventory false','gamerule spawnRadius 0','time set 1000','forceload add -32 -32 48 48','fill -24 65 -24 0 78 28 minecraft:air','fill 1 65 -24 28 78 28 minecraft:air','fill -24 64 -24 28 64 28 minecraft:grass_block','kill @e[type=!minecraft:player]','setworldspawn -4 65 -4'])rcon(cmd)
 if(!resumeDir){fs.writeFileSync(path.join(temp,'structures.json'),JSON.stringify({'127.0.0.1:25566:overworld:castle':{origin,wood:'oak',version:3}}));fs.writeFileSync(path.join(temp,'mission.json'),JSON.stringify({goals:[],index:0,autoRequested:false,continuous:false}))}
 child=fork(path.resolve('bot.js'),[],{execArgv:['--env-file-if-exists=.env'],env:{...process.env,MC_HOST:'127.0.0.1',MC_PORT:'25566',MC_USERNAME:'LayaCastleTest',MC_AUTH:'offline',BOT_LOG_DIR:temp,WEB_VIEWER:'0'},stdio:['ignore','pipe','pipe','ipc']})
 for(const stream of [child.stdout,child.stderr])stream.on('data',b=>{output=(output+b.toString()).slice(-30000)})
 let last='';child.on('message',m=>{if(m.type==='state'){state=m;const b=m.buildings?.[0],line=[m.auto?.phase,b?.phase,b?.built,b?.furnitureBuilt,m.recovery?.phase].join(' ');if(line!==last){console.log(line);last=line}}})
 await wait(()=>state?.ready);rcon('spawnpoint LayaCastleTest -4 65 -4');if(!resumeDir)for(const [item,n]of Object.entries({...requirements('castle'),cobblestone:requirements('castle').cobblestone+96,cooked_beef:48,stone_pickaxe:3}))rcon(`give LayaCastleTest minecraft:${item} ${n}`);await sleep(500)
 const progress=()=> (state.buildings?.[0]?.built||0)+(state.buildings?.[0]?.furnitureBuilt||0),initialBuilt=progress(),totalProgress=blueprint('castle').length+furnishingPlan('castle').length;child.send({type:'command',text:resumeDir?'!auto 이어가기':'!auto 유럽풍 성을 지어줘'});
 if(resumeDir&&totalProgress-initialBuilt<12){await wait(()=>state.auto.enabled||state.auto.phase==='목표 완료');assert.equal(state.recovery.resume?.kind,'mission');assert.equal(state.recovery.resume.request,state.auto.request);assert.deepEqual(state.buildings[0].origin,origin);afterDeath=structuredClone(state)}
 else{await wait(()=>progress()>=Math.max(36,Math.min(totalProgress,initialBuilt+12)),300000);beforeDeath=structuredClone(state);rcon('kill LayaCastleTest');await wait(()=>state?.recovery?.phase==='기존 목표 재개'&&state.auto.enabled,50000);afterDeath=structuredClone(state);assert.equal(afterDeath.auto.request,beforeDeath.auto.request);assert.deepEqual(afterDeath.buildings[0].origin,origin);assert(afterDeath.buildings[0].built>=beforeDeath.buildings[0].built)}
 await wait(()=>state?.auto?.phase==='목표 완료'&&state.buildings[0].complete,1800000);const completed=structuredClone(state),b=completed.buildings[0];assert.equal(b.built,blueprint('castle').length);assert.equal(b.furnitureBuilt,furnishingPlan('castle').length);assert(b.stages.every(s=>s.complete));assert(completed.minimap.cells.some(c=>c>0));child.send({type:'command',text:'!stop'});await wait(()=>!state.busy&&!state.auto.continuous)
 const queries=['11 66 4 minecraft:oak_door[half=lower]','11 66 11 minecraft:oak_door[half=lower]','4 71 4 minecraft:stone_bricks','18 71 18 minecraft:stone_bricks','5 70 5 minecraft:ladder','11 69 13 minecraft:air','11 71 13 minecraft:oak_planks','11 66 14 minecraft:white_bed[part=foot,facing=east]','12 66 14 minecraft:white_bed[part=head,facing=east]'];for(const q of queries)assert(rcon('execute if block '+q).includes('Test passed'),q)
 fs.mkdirSync('artifacts',{recursive:true});fs.writeFileSync('artifacts/castle-live.json',JSON.stringify({scope:'Production bot.js, provided materials before construction, disposable port 25566 only. Actual placement, real death, same goal/site/progress recovery and full structure/furniture completion. Does not measure autonomous collection of every material in a normal survival world.',beforeDeath:beforeDeath?{goal:beforeDeath.auto.request,building:beforeDeath.buildings[0]}:null,recordedRecovery:completed.recovery,afterDeath:{goal:afterDeath.auto.request,building:afterDeath.buildings[0]},complete:b,queries,minimap:{observedAt:completed.minimap.observedAt,knownTiles:completed.minimap.cells.filter(c=>c>0).length}},null,2)+'\n');console.log('PASS complete European castle, 4 towers/ladders, 2 doors, hollow furnished keep, real death/resume and minimap terrain observation')
}
main().catch(e=>{console.error(e);fs.mkdirSync('artifacts',{recursive:true});fs.writeFileSync('artifacts/castle-live-failure.json',JSON.stringify({error:e.message,state,output},null,2));if(process.env.CASTLE_RESUME_DIR)fs.cpSync(temp,process.env.CASTLE_RESUME_DIR,{recursive:true});process.exitCode=1}).finally(async()=>{child?.kill('SIGTERM');await sleep(700);fs.rmSync(temp,{recursive:true,force:true});process.exit(process.exitCode||0)})
