// Exercise the real command dispatcher and recorded-home navigation in the
// completed disposable castle. No administrative fixtures or building changes.
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{fork}=require('node:child_process')
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'mc-home-live-')),sleep=ms=>new Promise(r=>setTimeout(r,ms));let child,state,output=''
async function wait(predicate,timeout=90000){const until=Date.now()+timeout;while(Date.now()<until){if(predicate())return;if(child?.exitCode!=null)throw Error(output);if(state?.auto?.failures)throw Error(state.auto.reason);await sleep(100)}throw Error('Home timeout: '+JSON.stringify(state?.auto)+'\n'+output)}
async function main(){
 fs.writeFileSync(path.join(temp,'structures.json'),JSON.stringify({'127.0.0.1:25566:overworld:castle':{origin:{x:4,y:65,z:4},wood:'oak',version:3}}));fs.writeFileSync(path.join(temp,'mission.json'),JSON.stringify({request:'',goals:[],index:0,continuous:false,autoRequested:false}))
 child=fork(path.resolve('bot.js'),[],{execArgv:['--env-file-if-exists=.env'],env:{...process.env,MC_HOST:'127.0.0.1',MC_PORT:'25566',MC_USERNAME:'LayaHomeTest',MC_AUTH:'offline',BOT_LOG_DIR:temp,WEB_VIEWER:'0'},stdio:['ignore','pipe','pipe','ipc']});child.on('message',m=>{if(m.type==='state')state=m});for(const stream of [child.stdout,child.stderr])stream.on('data',b=>{output=(output+b).slice(-6000)})
 await wait(()=>state?.ready);assert(state.buildings[0].complete,'requires an actually completed disposable castle');child.send({type:'command',text:'성으로 돌아가'});await wait(()=>state.auto.request==='성으로 돌아가'&&state.auto.phase==='목표 완료');const arrived=structuredClone(state);assert.equal(arrived.auto.goals[0].type,'home');assert.equal(arrived.auto.goals[0].design,'castle');assert(Math.hypot(arrived.position.x-11.5,arrived.position.z-13.5)<1);assert.equal(arrived.position.y,66);assert(arrived.buildings[0].complete)
 child.send({type:'command',text:'!stop'});await wait(()=>!state.busy&&!state.auto.continuous);child.send({type:'command',text:'!auto 집으로 가'});await wait(()=>state.auto.request==='집으로 가'&&state.auto.phase==='목표 완료');assert.equal(state.auto.goals[0].type,'home');assert(Math.hypot(state.position.x-11.5,state.position.z-13.5)<1)
 fs.writeFileSync('artifacts/home-live.json',JSON.stringify({scope:'Production bot dispatcher, recorded completed castle, real gate/keep traversal, no administrative gameplay changes.',request:arrived.auto.request,goal:arrived.auto.goals[0],position:arrived.position,building:arrived.buildings[0]},null,2)+'\n');console.log('PASS natural castle return and automatic home return, actual gate and keep entry, completed-building preservation')
}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{child?.kill('SIGTERM');await sleep(700);fs.rmSync(temp,{recursive:true,force:true});process.exit(process.exitCode||0)})
