const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path')
const {validateGoals,createMissions}=require('../missions'),{materialPlan}=require('../acquisition'),{blueprint}=require('../structures'),{portalBlueprint,triangulate}=require('../endgame'),{createCampaign}=require('../campaign'),{Vec3}=require('vec3')
const registry=require('minecraft-data')('1.21.1')
assert.throws(()=>validateGoals({goals:[{type:'item',item:'made_up'}]},registry))
assert.throws(()=>validateGoals({goals:[{type:'item',item:'iron_sword',quantity:-1}]},registry))
assert.throws(()=>validateGoals({goals:[{type:'build',design:'unknown'}]},registry))
assert.equal(validateGoals({goals:[{type:'dragon'},{type:'build',design:'house'}]},registry).length,2)
const plan=materialPlan('stone_hoe',1,[{name:'dark_oak_log',count:8}]);assert(!JSON.stringify(plan).includes('unknown_source'));assert(JSON.stringify(plan).includes('cobblestone'));assert(!JSON.stringify(plan).includes('bamboo'))
for(const kind of ['cabin','house','warehouse','tower','bridge']){const cells=blueprint(kind);assert.equal(new Set(cells.map(p=>`${p.x},${p.y},${p.z}`)).size,cells.length);assert(cells.length>20)}
assert.equal(portalBlueprint(new Vec3(0,0,0)).length,10)
const target=triangulate({origin:{x:0,z:0},direction:{x:1,z:1}},{origin:{x:10,z:0},direction:{x:-1,z:1}});assert.equal(target.x,5);assert.equal(target.z,5)
assert.equal(triangulate({origin:{x:0,z:0},direction:{x:1,z:0}},{origin:{x:0,z:2},direction:{x:1,z:0}}),null)
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'mc-missions-')),campaign=createCampaign(path.join(temp,'campaign.json'))
assert.equal(campaign.snapshot({inventory:[{name:'dragon_egg',count:1}]}).complete,false)
campaign.record('dragon',{source:'server_entity_dead'});assert.equal(campaign.snapshot({inventory:[]}).complete,true)
async function main(){let inv=[],generation=0,executed=0;const bot={registry,inventory:{items:()=>inv,slots:[]},entity:{position:new Vec3(0,64,0)},game:{dimension:'overworld',difficulty:'normal'},food:20,health:20};const hooks={check:t=>{if(t!==generation)throw new Error('cancel')},token:()=>generation,isBusy:()=>false,run:fn=>fn(),acquire:async(name,count)=>{executed++;inv.push({name,count})},skills:{},world:{},structures:{},endgame:{},campaign,explore:async()=>{},log:()=>{}};const file=path.join(temp,'mission.json'),mission=createMissions(bot,hooks,file)
await mission.start('iron_sword');await mission.tick();assert.equal(mission.view().phase,'목표 완료');assert.equal(executed,1)
const resumed=createMissions(bot,hooks,file);assert.equal(resumed.view().goals[0].item,'iron_sword');assert.equal(resumed.view().enabled,false)
let failures=0;const fail=createMissions(bot,{...hooks,acquire:async()=>{failures++;throw new Error('No resource')}},path.join(temp,'fail.json'));await fail.start('diamond');for(let i=0;i<20;i++)await fail.tick();assert.equal(fail.view().enabled,false);assert.equal(failures,6);assert.match(fail.view().phase,/복구/)
assert(fail.deathCheckpoint(),'recoverable failure retains the saved objective');fail.stop({preserveIntent:true});fail.stop({preserveIntent:true});assert.equal(fail.deathCheckpoint().request,'diamond','repeated automatic pauses must preserve the same goal');const persisted=createMissions(bot,hooks,path.join(temp,'fail.json'));assert.equal(persisted.deathCheckpoint().request,'diamond');persisted.stop();assert.equal(persisted.deathCheckpoint(),null,'explicit stop must cancel death resumption');
const cancellable=createMissions(bot,{...hooks,acquire:async()=>{generation++;throw new Error('cancel')}},path.join(temp,'cancel.json'));await cancellable.start('diamond');await cancellable.tick();cancellable.stop();assert.equal(cancellable.view().index,0);assert.equal(cancellable.view().enabled,false)
fs.rmSync(temp,{recursive:true});console.log('PASS goal validation, recipe sources, structure uniqueness, portal geometry, triangulation, evidence-only victory, persisted queue, bounded retries, cancellation')}
main().catch(e=>{console.error(e);process.exit(1)})
const {parseKnownGoals}=require('../missions')
assert.deepEqual(parseKnownGoals('상자 만들고 조약돌 16개 보관해줘',registry).map(g=>[g.type,g.item,g.quantity||1]),[['item','chest',1],['store','cobblestone',16]])
assert.deepEqual(parseKnownGoals('집 짓고 밀 농사도 지어줘',registry).map(g=>g.type),['build','farm'])
assert.equal(parseKnownGoals('재료 모아서 철 무기 만들어줘',registry)[0].item,'iron_sword')
