const assert=require('node:assert/strict'),{nextTask}=require('../planner')
const item=(name,count=1)=>({name,count})
assert.equal(nextTask([]),'wood')
assert.equal(nextTask([item('oak_log',8)]),'wooden_pickaxe')
assert.equal(nextTask([item('wooden_pickaxe')]),'stone_pickaxe')
assert.equal(nextTask([item('stone_pickaxe')]),null)
assert.equal(nextTask([item('stone_pickaxe')],'iron_pickaxe'),'iron_pickaxe')
assert.equal(nextTask([item('iron_pickaxe')],'iron_pickaxe'),null)
console.log('PASS automatic task progression and goal completion')
