const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{Vec3}=require('vec3')
const {createRoutine}=require('../routine'),{createMissions,interpret}=require('../missions')
const registry=require('minecraft-data')('1.21.1'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'mc-routine-'))
let clock=1000000;const realNow=Date.now
function fixture(){
 let inv=[{name:'cooked_beef',count:8},{name:'stone_pickaxe',count:1},{name:'oak_log',count:4}],generation=0,farms=[]
 const calls=[],events=[],bot={registry,entities:{},health:20,food:20,time:{timeOfDay:1000},game:{dimension:'overworld'},entity:{position:new Vec3(0,64,0)},inventory:{items:()=>inv,slots:Array(46).fill(null)}}
 const hooks={continuous:true,check:t=>{if(t!==generation)throw Error('cancelled')},token:()=>generation,isBusy:()=>false,run:f=>f(),now:()=>clock,log:e=>events.push(e),skills:{equip:async()=>calls.push('equip'),eat:async()=>{calls.push('eat');bot.food=20},retreat:async()=>{calls.push('retreat');bot.entities={}}},structures:{allStatus:()=>[]},world:{farmStatus:()=>({farms}),farm:async()=>{calls.push('farm');return {title:'밀',complete:true,waiting:true,nextCheck:clock+30000,planted:24,plots:24,ripe:0,harvested:0}}},campaign:{snapshot:()=>({stages:[]})},acquire:async(name,count)=>{calls.push('acquire '+name);inv.push({name,count})},collector:{status:()=>({}),collect:async()=>calls.push('wood')},explorer:{status:()=>({visited:0}),observe:()=>calls.push('observe')},explore:async()=>{calls.push('explore');bot.entity.position=bot.entity.position.offset(8,0,0);return {}},near:async p=>{calls.push('home');bot.entity.position=p},food:async()=>{calls.push('food');return {waiting:true,nextCheck:clock+30000}}}
 return {bot,hooks,calls,events,setInventory:a=>inv=a,setFarm:f=>farms=f,cancel:()=>generation++,mission:()=>createMissions(bot,hooks,path.join(temp,Math.random()+'.json'))}
}
async function main(){try{Date.now=()=>clock
 assert.equal((await interpret('유럽풍 성 건축해줘',registry))[0].design,'castle','a castle command must not silently become a small house')
 const completed=fixture(),m=completed.mission();await m.start('iron_sword');await m.tick();assert.equal(m.view().phase,'목표 완료');assert.equal(m.view().index,1)
 await m.tick();assert(completed.calls.includes('explore'),'completed objective must continue real maintenance');assert.equal(m.view().index,1);assert.equal(m.view().request,'iron_sword');assert(m.view().continuous)
 m.stop();clock+=5000;const stopped=completed.calls.length;await m.tick();assert.equal(completed.calls.length,stopped,'explicit stop cancels both the objective and maintenance');assert(!m.view().continuous);assert.equal(m.deathCheckpoint(),null)
 const farm=fixture();farm.setFarm([{crop:'wheat',complete:true,planted:24,ripe:0,harvested:0}]);const fm=farm.mission();await fm.start('밀 수확해줘');await fm.tick();assert.equal(fm.view().index,0);await fm.tick();assert.equal(farm.calls.at(-1),'explore','growth deadline must yield to maintenance')
 farm.hooks.world.farm=async()=>{farm.calls.push('harvest');return {title:'밀',complete:true,waiting:false,planted:24,plots:24,ripe:0,harvested:16}}
 clock+=31000;await fm.tick();assert.equal(farm.calls.at(-1),'harvest');assert.equal(fm.view().index,1,'original harvest goal resumes after its deadline')
 const blocked=fixture();blocked.hooks.acquire=async()=>{blocked.calls.push('blocked');throw Error('No resource')};const bm=blocked.mission();await bm.start('diamond');for(let i=0;i<30&&bm.view().enabled;i++)await bm.tick();assert(!bm.view().enabled);assert(bm.view().autoRequested);assert(bm.view().continuous);assert.equal(bm.deathCheckpoint().request,'diamond')
 const pauseMoves=blocked.calls.filter(x=>x==='explore').length;await bm.tick();assert(blocked.calls.filter(x=>x==='explore').length>pauseMoves,'blocked goal must perform alternative work');clock+=31000;await bm.tick();assert(bm.view().enabled);assert(blocked.events.some(e=>e.type==='goal_retry'));assert.equal(bm.view().index,0)
 const pending=fixture();pending.hooks.commandPending=()=>true;const pm=pending.mission();await pm.tick();assert.equal(pending.calls.length,0,'pending command gets priority over a new maintenance action')
 const underground=fixture();underground.bot.entity.position.y=50;underground.hooks.structures.allStatus=()=>[{kind:'house',origin:{x:4,y:64,z:4}}];await createRoutine(underground.bot,underground.hooks).step(0);assert.equal(underground.calls[0],'home','return to the known surface base before seeking more resources')
 const failed=fixture();failed.hooks.explore=async()=>{failed.calls.push('bad route');throw Error('No path')};const r=createRoutine(failed.bot,failed.hooks);await r.step(0);clock+=2500;await r.step(0);assert.equal(failed.calls.filter(x=>x==='bad route').length,1,'failed action gets a cooldown instead of spinning');assert(failed.calls.includes('observe'));assert.equal(r.status().failures,1)
 const hungry=fixture();hungry.bot.food=12;await createRoutine(hungry.bot,hungry.hooks).step(0);assert.equal(hungry.calls[0],'eat')
 const threat=fixture();threat.bot.entities={1:{name:'zombie',type:'player',position:new Vec3(1,64,0)}};await createRoutine(threat.bot,threat.hooks).step(0);assert(!threat.calls.includes('retreat'),'players are never treated as hostile mobs')
 const cancelled=fixture();cancelled.hooks.explore=async()=>cancelled.cancel();const cr=createRoutine(cancelled.bot,cancelled.hooks);await assert.rejects(()=>cr.step(0),/cancelled/);assert(!cr.isRunning());assert(!cancelled.events.some(e=>e.type==='routine_result'&&e.ok),'cancelled actions must not be reported as completed')
 const save=path.join(temp,'saved.json');fs.writeFileSync(save,JSON.stringify({request:'diamond',goals:[{type:'item',item:'diamond',quantity:1}],index:0,autoRequested:true,continuous:true}));const loaded=createMissions(blocked.bot,blocked.hooks,save);assert(loaded.view().continuous);assert.equal(loaded.deathCheckpoint().request,'diamond');loaded.setContinuous(false);assert.equal(JSON.parse(fs.readFileSync(save)).continuous,false)
 console.log('PASS continuous activity after completion, crop growth multitasking, preserved blocked goal with recovery and retry, command priority, manual stop, underground return, route cooldown, eating, player exclusion, cancellation and saved preferences')
}finally{Date.now=realNow;fs.rmSync(temp,{recursive:true,force:true})}}
main().catch(e=>{console.error(e);process.exitCode=1})
