// Only the disposable server receives terrain/material/death fixtures.
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{execFileSync,fork}=require('node:child_process')
assert.equal(Number(process.env.MC_TEST_PORT||25566),25566)
const rcon=cmd=>execFileSync('docker',['exec','minecraft-laya-validation','rcon-cli',cmd],{encoding:'utf8',timeout:10000}),sleep=ms=>new Promise(r=>setTimeout(r,ms)),temp=fs.mkdtempSync(path.join(os.tmpdir(),'mc-routine-live-'))
let child,state,output='';const states=[]
async function wait(predicate,timeout=35000){const end=Date.now()+timeout;while(Date.now()<end){if(predicate())return;if(child?.exitCode!=null)throw Error('Bot exited: '+output.slice(-1500));await sleep(100)}throw Error('Timeout: '+JSON.stringify({auto:state?.auto?.phase,routine:state?.auto?.routine,position:state?.position,recovery:state?.recovery})+'\n'+output.slice(-2500))}
const events=()=>fs.existsSync(path.join(temp,'events.jsonl'))?fs.readFileSync(path.join(temp,'events.jsonl'),'utf8').trim().split('\n').filter(Boolean).map(JSON.parse):[]
async function main(){
 for(const cmd of ['gamerule doMobSpawning false','gamerule doDaylightCycle false','gamerule keepInventory false','gamerule spawnRadius 0','time set 1000','forceload add -64 -64 64 64','fill -40 65 -40 0 72 40 minecraft:air','fill 1 65 -40 40 72 40 minecraft:air','fill -40 64 -40 40 64 40 minecraft:grass_block','kill @e[type=!minecraft:player]','setworldspawn 0 65 0','fill 4 65 4 4 68 4 minecraft:oak_log','fill -6 65 4 -6 68 4 minecraft:oak_log'])rcon(cmd)
 fs.writeFileSync(path.join(temp,'mission.json'),JSON.stringify({goals:[],index:0,autoRequested:false,continuous:false}))
 child=fork(path.resolve('bot.js'),[],{execArgv:['--env-file-if-exists=.env'],env:{...process.env,MC_HOST:'127.0.0.1',MC_PORT:'25566',MC_USERNAME:'LayaRoutineTest',MC_AUTH:'offline',BOT_LOG_DIR:temp,WEB_VIEWER:'0'},stdio:['ignore','pipe','pipe','ipc']})
 for(const stream of [child.stdout,child.stderr])stream.on('data',b=>{output=(output+b.toString()).slice(-20000)})
 child.on('message',m=>{if(m.type==='state'){state=m;states.push({time:Date.now(),position:m.position,continuous:m.auto?.continuous,phase:m.auto?.phase,action:m.auto?.routine?.action,index:m.auto?.index,request:m.auto?.request})}})
 await wait(()=>state?.ready);await sleep(600);rcon('give LayaRoutineTest minecraft:cooked_beef 8');rcon('give LayaRoutineTest minecraft:stone_pickaxe 1');rcon('give LayaRoutineTest minecraft:oak_log 8');rcon('spawnpoint LayaRoutineTest 0 65 0');await sleep(400)
 child.send({type:'command',text:'!auto 나무곡괭이 만들어줘'});await wait(()=>state?.auto?.phase==='목표 완료'&&state.inventory.some(i=>i.name==='wooden_pickaxe'))
 const completed=structuredClone(state);await wait(()=>events().some(e=>e.type==='routine_result'&&e.ok&&e.action==='explore'));const afterExplore=structuredClone(state)
 assert.equal(afterExplore.auto.index,1);assert.equal(afterExplore.auto.request,completed.auto.request);assert(afterExplore.auto.continuous)
 const moved=Math.hypot(afterExplore.position.x-completed.position.x,afterExplore.position.z-completed.position.z);assert(moved>3,'goal completion must be followed by actual movement')
 console.log('Goal crafted, then autonomous movement:',moved.toFixed(1),'blocks')
 await wait(()=>state?.auto?.workKind==='routine'&&state.auto.routine.action==='explore',25000);const issued=Date.now();child.send({type:'command',text:'!auto 막대기 5개 만들어줘'})
 await wait(()=>state?.auto?.request==='막대기 5개 만들어줘'&&state.auto.phase==='목표 완료',15000);const switched=structuredClone(state);assert(switched.inventory.filter(i=>i.name==='stick').reduce((n,i)=>n+i.count,0)>=5);assert(!output.includes('진행 중인 작업을 먼저 중지'))
 console.log('New objective preempted maintenance and crafted sticks in',Date.now()-issued,'ms')
 // The life toggle preserves the current queue even when it interrupts movement.
 await wait(()=>state?.auto?.workKind==='routine',25000);const goal=state.auto.request,index=state.auto.index;child.send({type:'command',text:'자율생활 끄기'});await wait(()=>!state.auto.continuous&&!state.busy);assert.equal(state.auto.request,goal);assert.equal(state.auto.index,index)
 child.send({type:'command',text:'자율생활 켜기'});await wait(()=>state.auto.continuous);rcon('kill LayaRoutineTest');await wait(()=>state?.recovery?.phase==='기존 목표 재개'&&state.auto.continuous,40000);assert.equal(state.recovery.resume.kind,'routine');assert.equal(state.auto.request,goal);await wait(()=>!state.recovery.active&&state.auto.routine.steps>0)
 const afterDeath=structuredClone(state);child.send({type:'command',text:'!stop'});await wait(()=>!state.auto.continuous&&!state.auto.enabled&&!state.busy);const stopped=structuredClone(state);await sleep(5000);assert(!state.auto.continuous);assert.equal(state.auto.routine.steps,stopped.auto.routine.steps,'explicit stop must not keep running background tasks')
 fs.mkdirSync('artifacts',{recursive:true});fs.writeFileSync('artifacts/routine-live.json',JSON.stringify({scope:'Production bot.js on disposable port 25566; materials supplied before objectives. Real crafting, movement after completion, command preemption, life toggle, death recovery and manual stop. No fixtures in the user world.',completed:{goal:completed.auto.request,index:completed.auto.index,position:completed.position,inventory:completed.inventory},afterExplore:{position:afterExplore.position,moved,continuous:afterExplore.auto.continuous},switched:{goal:switched.auto.request,inventory:switched.inventory},afterDeath:{request:afterDeath.auto.request,index:afterDeath.auto.index,recovery:afterDeath.recovery},stopped:{continuous:state.auto.continuous,enabled:state.auto.enabled,steps:state.auto.routine.steps},events:events(),states},null,2)+'\n')
 console.log('PASS production bot: craft -> ongoing actual activity -> immediate new objective -> toggle preserves queue -> real death resumes life -> explicit stop cancels all activity')
}
main().catch(e=>{console.error(e);fs.mkdirSync('artifacts',{recursive:true});fs.writeFileSync('artifacts/routine-live-failure.json',JSON.stringify({error:e.message,state,output,events:events()},null,2));process.exitCode=1}).finally(async()=>{child?.kill('SIGTERM');await sleep(700);fs.rmSync(temp,{recursive:true,force:true});process.exit(process.exitCode||0)})
