const assert=require('node:assert/strict'),{buildRoadmap}=require('../survival-plan'),{allowedActions}=require('../qwen-planner')
const s={target:'iron_sword',health:20,inventory:[{name:'stone_pickaxe',count:1},{name:'oak_log',count:7},{name:'cobblestone',count:7}],nearby:[]}
assert.equal(buildRoadmap(s).next,'gather_stone');assert.equal(buildRoadmap(s).stoneNeeded,8)
assert.equal(buildRoadmap(s).ironKnowledge,'unknown');assert.equal(buildRoadmap(s).ironNeeded,2)
s.inventory[2].count=8;assert.equal(buildRoadmap(s).next,'prepare_furnace')
s.inventory.push({name:'furnace',count:1});s.inventory[2].count=0;assert.equal(buildRoadmap(s).next,'gather_iron')
s.inventory.push({name:'raw_iron',count:2});assert.equal(buildRoadmap(s).next,'smelt_iron')
s.inventory.pop();s.inventory.push({name:'iron_ingot',count:2});assert.equal(buildRoadmap(s).next,'iron_sword');assert(allowedActions(s).includes('iron_sword'))
s.inventory.push({name:'iron_sword',count:1});assert(buildRoadmap(s).steps.every(x=>x.status==='done'))
s.target='iron_pickaxe';assert.equal(buildRoadmap(s).ironNeeded,3);assert.equal(buildRoadmap(s).next,'gather_iron')
console.log('PASS weapon prerequisites, consumed furnace materials, smelting, target-specific quantities, actual completion')
