const assert=require('node:assert/strict'),fs=require('node:fs')
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'/tmp/laya-browser/node_modules/playwright')
;(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']})
 const page=await browser.newPage({viewport:{width:1440,height:1150}});const errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('http://127.0.0.1:3000/');await page.waitForFunction(()=>document.querySelector('#modelStatus').textContent.includes('실행 중'))
 assert.equal(await page.locator('#execute').isDisabled(),true)
 await page.locator('#command').fill('웹 화면 테스트: 철곡괭이 만들어 줘')
 await page.locator('#analyze').click();await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('판단 완료'))
 assert.equal(await page.locator('#choice').textContent(),'철곡괭이')
 const before=await page.request.get('http://127.0.0.1:3000/api/state').then(r=>r.json());const event=before.events.filter(e=>e.type==='decision').at(-1)
 await page.locator('#label').selectOption('iron_pickaxe');await page.locator('#correct').click();await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('정답을 저장'))
 const after=await page.request.get('http://127.0.0.1:3000/api/state').then(r=>r.json());assert.equal(after.corrections,before.corrections+1)
 // Remove only this test's correction; preserve all user records.
 const file='training/data/corrections.jsonl';const rows=fs.readFileSync(file,'utf8').split('\n').filter(Boolean).map(JSON.parse);fs.writeFileSync(file,rows.filter(r=>r.event_id!==event.id).map(r=>JSON.stringify(r)+'\n').join(''))
 const noCsrf=await page.request.post('http://127.0.0.1:3000/api/connect',{data:{}});assert.equal(noCsrf.status(),403)
 await page.locator('#connect').click();await page.waitForFunction(()=>document.querySelector('#botStatus').textContent.includes('재접속'))
 await page.locator('#disconnect').click();await page.waitForFunction(()=>document.querySelector('#botStatus').textContent.includes('미접속'))
 await page.screenshot({path:'artifacts/dashboard-desktop.png',fullPage:true})
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/dashboard-mobile.png',fullPage:true})
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile overflow')
 assert.deepEqual(errors,[])
 console.log('PASS dashboard: raw model decision, correction persistence, CSRF guard, bot connection lifecycle, desktop/mobile layout')
 await browser.close()
})().catch(e=>{console.error(e);process.exit(1)})
